/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check



/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    'gettingstarted',
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference' // Generate sidebar slice from docs/guides
        }
      ]
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api' // Generate sidebar slice from docs/guides
        }
      ]
    }

  ]

};



module.exports = sidebars;
